"""add currency to profitability_calculation

Revision ID: 77b9a9e018f9
Revises: 77ee8510ea43
Create Date: 2026-08-16 08:05:23.644619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77b9a9e018f9'
down_revision: Union[str, Sequence[str], None] = '77ee8510ea43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Added with a server default so this doesn't fail on a table that already has
    # rows (they all become "USD", matching every existing candidate/offer before
    # this change); the default is then dropped so new rows must specify a value
    # explicitly via the ORM, same as every other column here.
    op.add_column(
        'profitability_calculation',
        sa.Column('currency', sa.String(length=8), nullable=False, server_default='USD'),
    )
    op.alter_column('profitability_calculation', 'currency', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profitability_calculation', 'currency')
    # ### end Alembic commands ###
