"""initial schema

Revision ID: 77ee8510ea43
Revises: 
Create Date: 2026-08-15 21:03:25.143437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77ee8510ea43'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_run',
    sa.Column('query_text', sa.String(length=512), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETE', 'FAILED', name='run_status'), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_run'))
    )
    op.create_table('supplier',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('contact_email', sa.String(length=256), nullable=True),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier'))
    )
    op.create_table('integration_call_log',
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('provider_category', sa.String(length=64), nullable=False),
    sa.Column('provider_name', sa.String(length=64), nullable=False),
    sa.Column('request', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['search_run.id'], name=op.f('fk_integration_call_log_run_id_search_run'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_call_log'))
    )
    op.create_table('product_opportunity',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('demand_score', sa.Float(), nullable=False),
    sa.Column('competition_score', sa.Float(), nullable=False),
    sa.Column('trend_score', sa.Float(), nullable=False),
    sa.Column('avg_selling_price', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('raw_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['search_run.id'], name=op.f('fk_product_opportunity_run_id_search_run'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_opportunity'))
    )
    op.create_table('supplier_offer',
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('product_opportunity_id', sa.UUID(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('moq', sa.Integer(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('shipping_method', sa.String(length=64), nullable=True),
    sa.Column('shipping_cost', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_opportunity_id'], ['product_opportunity.id'], name=op.f('fk_supplier_offer_product_opportunity_id_product_opportunity'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_supplier_offer_supplier_id_supplier'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_offer'))
    )
    op.create_table('profitability_calculation',
    sa.Column('product_opportunity_id', sa.UUID(), nullable=False),
    sa.Column('supplier_offer_id', sa.UUID(), nullable=False),
    sa.Column('landed_cost', sa.Float(), nullable=False),
    sa.Column('selling_price', sa.Float(), nullable=False),
    sa.Column('marketplace_fee', sa.Float(), nullable=False),
    sa.Column('shipping_cost', sa.Float(), nullable=False),
    sa.Column('other_costs', sa.Float(), nullable=False),
    sa.Column('profit', sa.Float(), nullable=False),
    sa.Column('margin_pct', sa.Float(), nullable=False),
    sa.Column('roi_pct', sa.Float(), nullable=False),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_opportunity_id'], ['product_opportunity.id'], name=op.f('fk_profitability_calculation_product_opportunity_id_product_opportunity'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_offer_id'], ['supplier_offer.id'], name=op.f('fk_profitability_calculation_supplier_offer_id_supplier_offer'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profitability_calculation'))
    )
    op.create_table('recommendation',
    sa.Column('product_opportunity_id', sa.UUID(), nullable=False),
    sa.Column('profitability_calculation_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('BUY_TEST', 'WATCH', 'REJECT', name='decision'), nullable=False),
    sa.Column('rationale', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_opportunity_id'], ['product_opportunity.id'], name=op.f('fk_recommendation_product_opportunity_id_product_opportunity'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profitability_calculation_id'], ['profitability_calculation.id'], name=op.f('fk_recommendation_profitability_calculation_id_profitability_calculation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation')
    op.drop_table('profitability_calculation')
    op.drop_table('supplier_offer')
    op.drop_table('product_opportunity')
    op.drop_table('integration_call_log')
    op.drop_table('supplier')
    op.drop_table('search_run')
    # ### end Alembic commands ###
    # Manually added: dropping a table does not drop the Postgres ENUM type(s) its
    # columns used, so without this, downgrading and then upgrading again fails with
    # "type already exists".
    sa.Enum(name='decision').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='run_status').drop(op.get_bind(), checkfirst=True)
