"""add operations_approval table

Revision ID: ad4719b9252d
Revises: 77b9a9e018f9
Create Date: 2026-08-16 08:20:52.948950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad4719b9252d'
down_revision: Union[str, Sequence[str], None] = '77b9a9e018f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operations_approval',
    sa.Column('product_opportunity_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='approval_status'), nullable=False),
    sa.Column('external_reference', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_opportunity_id'], ['product_opportunity.id'], name=op.f('fk_operations_approval_product_opportunity_id_product_opportunity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operations_approval'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operations_approval')
    # ### end Alembic commands ###
    # Manually added: dropping the table does not drop the Postgres ENUM type its
    # status column used (see the initial-schema migration for the same fix).
    sa.Enum(name='approval_status').drop(op.get_bind(), checkfirst=True)
